
#
# Module Manifest for Module 'PsoProgressButton.psd1
#
# This manifest file is a PowerShell hashtable with all technical requirements for this module
# This module was autogenerated by ISESteroids (http://www.isesteroids.com)
#
# Generated: 2022-11-02
#

@{

# Module Loader File
RootModule = 'loader.psm1'

# Version Number
ModuleVersion = '1.0'

# compatible PowerShell Versions
CompatiblePSEditions = @()

# Unique Module ID
GUID = '34823376-b999-481c-8dd0-5a34d7ebc047'

# Module Author
Author = 'Dr. Tobias Weltner'

# Company
CompanyName = 'powershell.one'

# Copyright
Copyright = '(c) 2022 Dr. Tobias Weltner. MIT License'

# Module Description
Description = 'Provides easy access to controlling animations and progress indicators for taskbar buttons on Windows operating systems'
}